<?php
/**
 * Provision demo databases via cPanel UAPI.
 *
 * One-shot: uploads itself, hits /cgi/... to create:
 *   - webmed6_crmdemo (with user webmed6_crmdemo)
 *   - webmed6_cmsdemo (with user webmed6_cmsdemo)
 * Then loads both schema.sql files into their respective DBs.
 * DELETE THIS FILE from the server immediately after running.
 *
 * Usage (from the browser, once uploaded to /public_html/_deploy/):
 *   https://netwebmedia.com/_deploy/_provision_demo_dbs.php?key=<one-time-secret>
 *
 * The UAPI calls below assume this script runs AS cPanel user webmed6 (i.e. executed
 * inside that account's public_html). cPanel will pick up the session user from the
 * running context; no credentials embedded.
 */

// --- Guard: require a one-time key so a scraper doesn't trigger provisioning.
$expected_key = getenv('NWM_PROVISION_KEY') ?: 'nwm-provision-2026-04-20';
if (($_GET['key'] ?? '') !== $expected_key) {
    http_response_code(403);
    echo "forbidden";
    exit;
}

header('Content-Type: text/plain; charset=utf-8');

function uapi($module, $func, $args) {
    $url = '/usr/local/cpanel/bin/uapi --output=json ' . escapeshellarg($module) . ' ' . escapeshellarg($func);
    foreach ($args as $k => $v) {
        $url .= ' ' . escapeshellarg($k . '=' . $v);
    }
    $out = shell_exec($url);
    return json_decode($out, true);
}

function crmsafe_pass() {
    // Deterministic demo password (readable from cfg) — override in .netwebmedia-config-demo.php
    return 'Nwm@Demo2026!Sx';
}

$results = [];

// --- 1. Create DBs
foreach (['webmed6_crmdemo', 'webmed6_cmsdemo'] as $db) {
    $r = uapi('Mysql', 'create_database', ['name' => $db]);
    $results[] = ['create_db' => $db, 'result' => $r];
}

// --- 2. Create users (if not exist) with same name as the DB
foreach (['webmed6_crmdemo', 'webmed6_cmsdemo'] as $user) {
    $r = uapi('Mysql', 'create_user', ['name' => $user, 'password' => crmsafe_pass()]);
    $results[] = ['create_user' => $user, 'result' => $r];
}

// --- 3. Grant ALL on DB to matching user
foreach ([['webmed6_crmdemo', 'webmed6_crmdemo'], ['webmed6_cmsdemo', 'webmed6_cmsdemo']] as $pair) {
    $r = uapi('Mysql', 'set_privileges_on_database', [
        'user' => $pair[1],
        'database' => $pair[0],
        'privileges' => 'ALL PRIVILEGES',
    ]);
    $results[] = ['grant' => $pair, 'result' => $r];
}

// --- 4. Load schemas
$schemas = [
    'webmed6_crmdemo' => __DIR__ . '/../crm-demo/api/schema.sql',
    'webmed6_cmsdemo' => __DIR__ . '/../cms-demo/schema.sql',
];
foreach ($schemas as $db => $path) {
    if (!file_exists($path)) {
        $results[] = ['load_schema' => $db, 'error' => "missing $path"];
        continue;
    }
    $cmd = 'mysql -u' . escapeshellarg($db) . ' -p' . escapeshellarg(crmsafe_pass())
         . ' ' . escapeshellarg($db) . ' < ' . escapeshellarg($path) . ' 2>&1';
    $out = shell_exec($cmd);
    $results[] = ['load_schema' => $db, 'output' => trim($out) ?: 'ok'];
}

// --- 5. Write config.local.php files with the demo DB password
$configs = [
    __DIR__ . '/../crm-demo/api/config.local.php',
    // CMS demo doesn't have a PHP backend in this static setup — skip unless api-php-demo exists
];
foreach ($configs as $cfgPath) {
    $dir = dirname($cfgPath);
    if (!is_dir($dir)) continue;
    $contents = "<?php\n"
              . "// Auto-generated by _provision_demo_dbs.php — do NOT commit.\n"
              . "if (!defined('DB_PASS')) define('DB_PASS', " . var_export(crmsafe_pass(), true) . ");\n";
    file_put_contents($cfgPath, $contents);
    chmod($cfgPath, 0640);
    $results[] = ['wrote_config' => $cfgPath];
}

echo json_encode($results, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
echo "\n\nDONE. Delete this file from the server now.\n";
